# Generated by Django 3.0.5 on 2020-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syslog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device id')),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Date')),
                ('program', models.CharField(blank=True, max_length=255, null=True, verbose_name='Programa')),
                ('msg', models.CharField(blank=True, max_length=600, null=True, verbose_name='Message')),
                ('seq', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'syslog',
            },
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['device_id'], name='device_id_idx'),
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['timestamp'], name='timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['program'], name='program_idx'),
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['msg'], name='msg_idx'),
        ),
    ]
