# Generated by Django 3.0.5 on 2020-07-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterSysLogApp', '0002_create_default_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApnSyslog',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(
                    blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=600, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('forward', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'queries',
            },
        ),
        migrations.AddIndex(
            model_name='apnsyslog',
            index=models.Index(fields=['timestamp'], name='timestamp_apn_idx'),
        ),
        migrations.AddIndex(
            model_name='apnsyslog',
            index=models.Index(fields=['domain'], name='domain_idx'),
        ),
        migrations.AddIndex(
            model_name='apnsyslog',
            index=models.Index(fields=['client'], name='client_idx'),
        ),
    ]
